# Generated by Django 2.2.9 on 2020-01-21 10:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='participate_points',
        ),
        migrations.AddField(
            model_name='homepage',
            name='mycontent',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(blank=False, max_length=255, null=True, required=True))]))], blank=True, null=True),
        ),
    ]
