# Generated by Django 2.2.9 on 2020-01-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200121_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='mycontent',
            new_name='participate_points',
        ),
    ]
