# Generated by Django 2.2.9 on 2020-01-27 08:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('flex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flex_page',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('contents', wagtail.core.fields.StreamField([('img_upload', wagtail.core.blocks.StructBlock([]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Presentation and Document Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
