# Generated by Django 2.2.9 on 2020-01-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
