# Generated by Django 2.2.9 on 2020-01-27 09:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_auto_20200127_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex_page',
            name='contents',
            field=wagtail.core.fields.StreamField([('doc', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('doc', wagtail.documents.blocks.DocumentChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
