# Generated by Django 2.2.9 on 2020-01-21 07:00

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('flex', '0003_delete_flexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.CharBlock(blank=False, max_length=255, null=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flex_page',
                'verbose_name_plural': 'Flex pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
