# Generated by Django 2.2.9 on 2020-01-27 09:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('flex', '0004_auto_20200127_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='contents',
            field=wagtail.core.fields.StreamField([('doc', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('doc', wagtail.documents.blocks.DocumentChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Flex_page',
        ),
    ]
