# Generated by Django 2.2.9 on 2020-01-27 13:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_auto_20200127_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='contents',
            field=wagtail.core.fields.StreamField([('doc', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('doc', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, null=True),
        ),
    ]
