# Generated by Django 2.2.9 on 2020-01-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshoplistingpage',
            old_name='custom_title',
            new_name='custom_heading',
        ),
    ]
