# Generated by Django 2.2.9 on 2020-01-29 13:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20200129_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetailpage',
            name='description',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='workshopdetailpage',
            name='objectives',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
