# Generated by Django 2.2.9 on 2020-01-30 12:38

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_remove_workshopdetailpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopdetailpage',
            name='objectives',
        ),
        migrations.AddField(
            model_name='workshopdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link']))])), ('full_richtext', streams.blocks.RichtextBlock()), ('simple_richtext', streams.blocks.SimpleRichtextBlock())], blank=True, null=True),
        ),
    ]
